services/web/project/models.py
from flask_login import UserMixin
from project import db


class User(UserMixin, db.Model):  # type: ignore
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(128), unique=True, nullable=False)
    active = db.Column(db.Boolean(), default=True, nullable=False)

    def __init__(self, email):
        self.email = email

    def __repr__(self):
        return f"<{self.id} | {self.email} | {self.active}>"

services/web/project/user_login/models.py
import datetime
from project import db


class LoginCode(db.Model):  # type: ignore
    __tablename__ = "login_code"

    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(128), nullable=False)
    code = db.Column(db.String(6), nullable=False)
    try_count = db.Column(db.Integer(), default=0)
    create_datatime = db.Column(db.DateTime(), default=datetime.datetime.now())

services/web/project/__init__.py
import os
from pydantic import BaseSettings, SecretStr

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail


class MailSettings(BaseSettings):
    MAIL_SERVER: str
    MAIL_PORT: int
    MAIL_USE_TLS: bool
    MAIL_USE_SSL: bool
    MAIL_DEFAULT_SENDER: str
    MAIL_USERNAME: str
    MAIL_PASSWORD: str


app = Flask(__name__)
env_config = os.getenv("APP_SETTINGS", "config.DevelopmentConfig")
app.config.from_object(env_config)
app.config.update(MailSettings())  # type: ignore


db = SQLAlchemy(app)


login_manager = LoginManager()
login_manager.login_view = "user_login.login_get"
login_manager.init_app(app)

mail_manager = Mail(app)

from .models import User  # noqa: E402


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


from project.user_profile import user_profile_blueprint  # noqa: E402
app.register_blueprint(user_profile_blueprint)

from project.user_login import user_login_blueprint  # noqa: E402
app.register_blueprint(user_login_blueprint)

from project.views import main as main_blueprint  # noqa: E402
app.register_blueprint(main_blueprint)

# from project import views  # noqa: E402

services/web/project/user_login/__init__.py
from .views import user_login as user_login_blueprint

services/web/project/user_login/controllers.py
from dataclasses import dataclass
from random import randint
from project import db, mail_manager
from project.models import User
from project.user_login.models import LoginCode
from flask_mail import Message


MAX_LOGIN_CODE_TRY = 3


@dataclass
class CheckCode:
    is_valid: bool
    try_count: int = 0


def send_code(email: str):
    code = str(randint(0, 999999)).rjust(6, '0')

    login_code = LoginCode(email=email, code=code)
    db.session.add(login_code)
    db.session.commit()

    msg = Message("You code", recipients=[email])
    msg.body = f"You code: {code}"
    mail_manager.send(msg)


def check_code(email: str, code: str):
    login_code = LoginCode.query.filter_by(email=email) \
        .order_by(LoginCode.create_datatime).all()[-1]
    login_code.try_count += 1
    db.session.commit()
    
    if code == login_code.code:
        return CheckCode(is_valid=True)
    
    return CheckCode(
        is_valid=False, 
        try_count=login_code.try_count
    )


def get_user(email):
    user = User.query.filter_by(email=email).first()
    if not user:
        user = User(email=email)
        db.session.add(user)
        db.session.commit()
    return user

services/web/project/user_login/views.py
import email
import json
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
)
from flask_login import login_user, login_required, logout_user
from pydantic import BaseModel, EmailStr, ValidationError, validator
from flask_pydantic import validate

from .controllers import get_user, send_code, check_code
from .controllers import CheckCode, MAX_LOGIN_CODE_TRY


user_login = Blueprint('user_login', __name__)


class LoginRequestModel(BaseModel):
    email: EmailStr
    code: str | None
    remember: bool | None

    @validator("email")
    def to_email_str(cls, email: str):
        return EmailStr(email)

    @validator("code")
    def empty_str(cls, code: str):
        return code if len(code) else "_"

    @validator("remember")
    def to_bool(cls, remember: str):
        return True if remember else False


@user_login.route('/login', methods=["GET"])
def login_get():
    return render_template("user_login/login_email.html", data=None)


@user_login.route('/login', methods=["POST"])
@validate()
def login_post():

    try:
        data = LoginRequestModel(**request.form)  # type: ignore
    except ValidationError as e:
        print(e)
        template = "user_login/login_code.html" if request.form.get("email") \
            else "user_login/login_email.html"
        return render_template(
            template,
            data=None,
            errors=json.loads(e.json())
        )

    if data.code:
        code_info: CheckCode = check_code(data.email, data.code)
        code_try_left = MAX_LOGIN_CODE_TRY - code_info.try_count
        if code_info.is_valid:
            user = get_user(data.email)
            login_user(user, remember=data.remember)
            return redirect(url_for('user_profile.profile'))
        elif code_try_left > 0:
            flash(f"Неверный код. Осталось  попыток: {code_try_left}.")
            return render_template("user_login/login_code.html", data=data)
        else:
            flash("Неверный код. Проверьте Email и попробуйте снова.")
            return render_template("user_login/login_email.html", data=data)
    else:
        send_code(data.email)
        return render_template("user_login/login_code.html", data=data)


@user_login.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

services/web/project/user_profile/__init__.py
from .views import user_profile as user_profile_blueprint

services/web/project/user_profile/views.py
from flask import (
    Blueprint,
    render_template,
)
from flask_login import login_required, current_user


user_profile = Blueprint('user_profile', __name__)


@user_profile.route("/profile")
@login_required
def profile():
    return render_template("user_profile/profile.html", email=current_user.email)

services/web/project/views.py
from flask import (
    Blueprint,
    render_template,
    send_from_directory,
    request,
)
from werkzeug.utils import secure_filename
from project import db, app
from project.models import User

import os


main = Blueprint('main', __name__)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/static/<path:filename>")
def staticfiles(filename):
    return send_from_directory(app.config["STATIC_FOLDER"], filename)


@main.route("/media/<path:filename>")
def mediafiles(filename):
    return send_from_directory(app.config["MEDIA_FOLDER"], filename)


@main.route("/upload", methods=["GET", "POST"])
def upload_file():
    if request.method == "POST":
        file = request.files.get("file")
        if file and file.filename:
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config["MEDIA_FOLDER"], filename))
    return """
    <!doctype html>
    <title>upload new File</title>
    <h3>Upload your media file</h3>
    <form action="" method=post enctype=multipart/form-data>
      <p><input type=file name=file><input type=submit value=Upload>
    </form>
    """

services/web/project/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                На главную
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('user_profile.profile') }}" class="navbar-item">
                                Профиль
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('user_login.login_get') }}" class="navbar-item">
                                Войти
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('user_login.logout') }}" class="navbar-item">
                                Выйти
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

services/web/project/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Example
</h1>
<h2 class="subtitle">
  Easy app in Flask.
</h2>
{% endblock %}

services/web/project/templates/user_login/login_code.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Отправили код на почту</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
            <!--{% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}-->

            {% for message in messages %}
                <div class="notification is-danger">
                    {{ message }}
                </div>
            {% endfor %}
        {% endwith %}
        {% for error in errors %}
            <div class="notification is-danger">
                {{ " ".join([errors[0]["loc"][0].capitalize(), errors[0]["msg"]]) }}.
            </div>
        {% endfor %}
        <form method="POST" action="/login">
            
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" readonly="readonly" value="{{ data.email }}">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="code" placeholder="Ваш Код" autofocus="">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox"> 
                    Запомнить устройство
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Отправить код</button>
        </form>
    </div>
</div>
{% endblock %}

services/web/project/templates/user_login/login_email.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Войти</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-success">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}
        {% if errors %}
            <div class="notification is-danger">
                {{ " ".join([errors[0]["loc"][0].capitalize(), errors[0]["msg"]]) }}.
            </div>
        {% endif %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Ваш Email" autofocus="" value="{{ data.email }}">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth" id="send_code">Отправить код</button>
        </form>
    </div>
</div>
{% endblock %}

services/web/project/templates/user_profile/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ email }}!
</h1>
{% endblock %}